Add docker-compose.yml for MongoDB instance
galnir/Master-Bot pull request #614
Opened 2021-09-06 04:31 UTC by rafaeldamasceno

Adds a MongoDB instance to a docker-compose stack.

2021-09-09 17:31 UTC, kfirmeg requested changes
Tried to test this and couldn't make it work with lines 8-10 in the docker-compose.yml file. 
Unless you found some way to make it work with the user and pass I suggest you remove lines 8-10 so it can run.
Other than that seems to run great👍, thanks for the addition.

2021-09-13 00:12 UTC, rafaeldamasceno commented
For me it works exactly like this and the following line on the `config.json` file:
```json
  "mongo_URI": "mongodb://master-bot:admin@mongo:27017/",
````

2021-09-13 09:27 UTC, kfirmeg approved these changes
Tested again with that URI and it worked. I mistakenly added something unnecessary to the URI before, causing the former malfunction.
Works great 👍

2021-09-13 09:27 UTC, galnir approved these changes

2021-09-13 09:27 UTC, merged